### ISSUE TITLE
hangs on pubkey authentication

### ISSUE THREAD

**Issue by haliphax** [M-griffin/EtherTerm#1]
I have an existing key for connecting to my system in `~/.ssh`. Even though I have a username and password set in `dialdirectory.xml`, it uses the pubkey. On the BBS side of things, I see 2 notices of `pubkey accepted for user 'haliphax'`, but EtherTerm hangs like it's still waiting for a response. If I rename `~/.ssh` before launching EtherTerm, it honors the username and password set in the XML file and connects just fine. So, this is really two issues:

1. If username and password are set for an SSH host, but a pubkey is found, it does not honor the XML settings for the host
2. Pubkey authentication hangs EtherTerm

**Comment by M-griffin** [comment]
Public Key Authentication is now fixed and tested with x84.  
Proper usage is to leave the password field blank in the xml file.  <-> If the XML file has blank fields, EtherTerm will prompt the user for a login username, followed by a password.  When using Public Key just leave the password prompt empty and hit [Enter] to automatically use the public key located in your [home] ~/.ssh folder.

https://github.com/M-griffin/EtherTerm/commit/a5ebeb73a53d9261e71c462d0dffeb4ba67e0ac9

**Comment by M-griffin** [comment]
test
