### ISSUE TITLE
Split Makefiles into debug and release builds

### ISSUE THREAD

**Issue by M-griffin** [M-griffin/EtherTerm#14]
Default currently is the DEBUG build. The release builds gains more optimizations and less extra debug code which speeds up the output display considerably.

**Comment by jquast** [comment]
you shouldn't have to make new files, just use environment variable ``DEBUG=1 make ...``
```
ifdef DEBUG
        <add debug flags to CC>
endif
```

**Comment by M-griffin** [comment]
Ahh too late, already did it.  :)  But i'll note it cause eventually i'll go to wither cmake or autotools instead of having separate files for each OS.

This is completed at the moment 
https://github.com/M-griffin/EtherTerm/commit/1ff20918488e73fe954c236a8f264765600fb761
