### ISSUE TITLE
Toggle for displaying incomplete ESC Sequences

### ISSUE THREAD

**Issue by M-griffin** [M-griffin/EtherTerm#15]
Right now all invalid ESC sequences are displayed for debugging purposes.  I've noticed on very large intro screens on Synchronet that random ESC sequences are coming over incomplete.  I've double checked with raw socket reads on Winfows, Linux and OSX that this is not a parsing error and appears to be Synchronet issue.  

I believe it's a good idea to setup a toggle remove invalid sequence from displaying to avoid the appearance of artifacts on the screen for release builds, but allow them during debug builds for testing.

**Comment by jquast** [comment]
Your decoding is incremental, right? if a read() call returns ``\x1b[`` and a subsequent call returns ``0m``, it is still interpreted as sgr0, right?

**Comment by M-griffin** [comment]
Yes, that is correct.  However in this instance,  i'm seeing ESC,  or ESC[, ESC[0  with normal characters after it (not even between socket calls),  So it appears to be lost in transmission.  I'm looking at the socket recv() prior to any parsing and this occurs when I connect to Pharcyde BBS which has a very long 3000 line into ANSI which i use for testing display speed.  I'm wondering if syncterm is sending too large of a buffer or something, but it's very random and not always the same place.  I've only seen this occur when connecting to Synchronet as of this moment, I haven't seen any issues with my own welcome and logoff screens which are almost as large.

I've also noticed that Syncterm sends random NULL characters \0 when connections are waiting for input like every 15/30 seconds.. like 50 or so in a row.  So I had to put some code to ignore null bytes.  Very annoying Synchronet is.  :)

**Comment by M-griffin** [comment]
Sweet, I just did a test in a raw terminal telnet in linux, and got the same issue, so I know it's not EtherTerm.  I took a screen cap too:

https://dl.dropboxusercontent.com/u/92792939/pharcyde.png

**Comment by jquast** [comment]
Use script(1) to get a capture.

**Comment by jquast** [comment]
How are you connecting to a cp437-encoded bbs like Pharcyde from putty?

**Comment by M-griffin** [comment]
Not Putty,  Gnome Ternimal.  In Linux Mint (gnome) The default GUI gnome terminal accepts echo -e "\033%@" and "\033(U" and switches to ANSI perfectly.  Then I used straight console telnet to connect.  I usually only use putty in Windows.

**Comment by M-griffin** [comment]
This has become stale.  Code will be looked over and re-implemented and tested.
