### ISSUE TITLE
typeahead is not possible: input is lost/unbuffered

### ISSUE THREAD

**Issue by jquast** [M-griffin/EtherTerm#16]
If the output routine is busy (drawing a long ansi, for example), then any input received on keyboard is lost.

For interactive programs like an editor with a fast typist like myself, it is entirely possible that keyboard input may be lost.

Reproduce: telnet to 1984.ws, login, while artwork is displayed, "<space>y<return>" should quickly skip past this script.  However, some or all of such input is lost, as top.py displays artwork slowly, and when the prompt is finally displayed, no input is given.

**Comment by M-griffin** [comment]
Ah, yes, this is because at the moment i don't have threading setup, so if the main program thread is buzy then it has to finish, it does check for input between each recv() on the socket, but in this instance it could be missed.  This is on the TODO list.  Thanks for the reminder.

**Comment by M-griffin** [comment]
This should now be fixed with the latest update.
commit 96c63f2bc90450057e692b22ee850d580cea24bf
