### ISSUE TITLE
Windows 8, Window Switching Issue After Full Screen

### ISSUE THREAD

**Issue by M-griffin** [M-griffin/EtherTerm#17]
Report of Windows 8, Window Switching Issue After Full Screen.  Crashes.

**Comment by grymmjack** [comment]
I can test anything in this regard you need.

**Comment by M-griffin** [comment]
Just made a few updates to the window switching code for windows only.  Here is a link to Test Demo:  https://dl.dropboxusercontent.com/u/92792939/EtherTerm%20Demo2.5%20-%20Win8.zip  let me know if this solves your issues then i'll commit the changes.  :+1:   Thanks.

**Comment by M-griffin** [comment]
Issues is now reported as fixed.  
https://github.com/M-griffin/EtherTerm/commit/df591eb19177872f72f16fa2e7c2a31fd5755068
