### ISSUE TITLE
can't launch from another location

### ISSUE THREAD

**Issue by haliphax** [M-griffin/EtherTerm#2]
I have to drop into the directory where the `EtherTerm` binary is located before launching it. I can't, for instance do this, if I put the `EtherTerm` binary into a folder named `EtherTerm` in my home folder:

    haliphax@oddnetwork:~$ EtherTerm/EtherTerm

**Comment by M-griffin** [comment]
Thanks for the Report. 
Path Detection has been added.  You can now execute with a path string from any folder including without changing to the current working directory.  Double clicking on the Executable in the OSX desktops now works correctly also.
