### ISSUE TITLE
EtherTerm/assets/vga8x16.bmp, missing pixel on CP437 character 199

### ISSUE THREAD

**Issue by aeonfluxcapacitor** [M-griffin/EtherTerm#20]
One of the line drawing characters, ASCII 199 is missing a pixel on the right center to make it a right side line connection. Without that pixel its a duplicate of character 186.
![image](https://cloud.githubusercontent.com/assets/13187655/8512352/f865b250-2303-11e5-83e6-14a4798341f1.png)

Should be:

![image](https://cloud.githubusercontent.com/assets/13187655/8512516/c327f3ca-230b-11e5-9e37-7337b9a89274.png)

Only noticed this as I was comparing different CP437 fonts and images I'd found around the web like this great article:
http://nerdlypleasures.blogspot.com/2015/04/ibm-character-fonts.html

**Comment by aeonfluxcapacitor** [comment]
Also noticed that character 152 (ÿ) is missing part of the umlaut, likely also an error?

**Comment by M-griffin** [comment]
Awesome, thank you for the feed back! I've had to do a lot of editing and recreation on my own so if I miss something thanks for pointing it out.  I'll fix those up.

**Comment by M-griffin** [comment]
Bitmap is now fixed, thanks again for the heads up.
Fixed applied in commit: 09d13070debae3d311fdcbf537e7b795b75e6b63

**Comment by aeonfluxcapacitor** [comment]
No problem! Thanks for the fix! :)
