### ISSUE TITLE
Automatic builds for Linux, OSX, Windows, and FreeBSD

### ISSUE THREAD

**Issue by jquast** [M-griffin/EtherTerm#5]
I will use my existing build infrastructure (TeamCity) to provide automatic builds.
- I need to add Windows and FreeBSD slaves to my build environment.
- I might also need to add an Arch Linux build slave -- however it might be much more convenient to make an Arch Linux "AUR", which allows Arch Linux users to build themselves, i have some experience with this, as does @tehmaze.
- If I provide a Windows VPS (Azure?), I hope you can help prepare it with the necessary build environment? What OS would be best, Windows 2012 server?

**Comment by M-griffin** [comment]
Thanks man!!  2012 should be good I suppose. That's a new one for me, I'll get it working somehow.

**Comment by M-griffin** [comment]
Which reminds me, i should get a vmware setup again for FreeBSD for testing as well.

**Comment by M-griffin** [comment]
Think i'll close this up, where has all the time gone..  :)
