### ISSUE TITLE
[0.4.0-Alpha] Hardcoded paths in build

### ISSUE THREAD

**Issue by bastetfurry** [M-griffin/EtherTerm#54]
When trying to make the Makefile in the ./linux directory someone gets this result:
```
bastetfurry@katzenrechner:~/compile/EtherTerm/linux$ make
----------Building project:[ EtherTerm - Debug ]----------
make[1]: Verzeichnis „/home/bastetfurry/compile/EtherTerm/linux“ wird betreten
/usr/bin/g++  -c  "/home/blue/code/EtherTerm/src/input_handler.cpp" -g -O0 -pedantic -W -std=c++11 -Wall   -o ./Debug/up_src_input_handler.cpp.o -I. -I. -I.. -I../src 
g++: error: /home/blue/code/EtherTerm/src/input_handler.cpp: Datei oder Verzeichnis nicht gefunden
g++: fatal error: no input files
compilation terminated.
EtherTerm.mk:98: recipe for target 'Debug/up_src_input_handler.cpp.o' failed
make[1]: *** [Debug/up_src_input_handler.cpp.o] Error 1
make[1]: Verzeichnis „/home/bastetfurry/compile/EtherTerm/linux“ wird verlassen
Makefile:4: recipe for target 'All' failed
make: *** [All] Error 2
```

This fails because there are hardcoded paths in the Makefile.

**Comment by ftoledo** [comment]
Replacing thats paths permit to compile. Thanks!

**Comment by M-griffin** [comment]
Note to self, add a make file command to clear local directory paths and use current working folder.

**Comment by M-griffin** [comment]
This has now been corrected with the latest PR #58

**Comment by M-griffin** [comment]
Actually going to re-open this. 
Windows, Linux, and OSX are now fixed.  I still have to update FreeBSD once i get the VM up and running again.  Once that is fixed i'll close this.

**Comment by M-griffin** [comment]
Windows, Linux and OSX builds should be all fixed.  I'm working on a new FreeBSD VM install to update these makes files as time permits for master first, then i'll merged and rework for the later branches.

**Comment by M-griffin** [comment]
FreeBSD should be good now, And changes have been merged back to master.  I should probably write up a quick text for install dependencies when i get a moment.
