### ISSUE TITLE
Wasn't able to install on macOS

### ISSUE THREAD

**Issue by squintgit** [M-griffin/EtherTerm#68]
Spent an hour trying to install this software. Eager to get off SyncTerm and onto something else.

Would love a macOS install script or something. I am running macOS Mojave 10.14.2.

**Comment by m00-git** [comment]
install homebrew then
`brew install sdl2 sdl2_net libssh`
`make clean-osx`
`make osx`

**Comment by M-griffin** [comment]
Thanks m00-git for replying.

I've been away from the project a little but, but last on High Sierra, and installing Catalina now and will double check the builds are working on the latest OSX next.  And then hopefully get a little more time to finish more features and get it out of a demo state.

**Comment by M-griffin** [comment]
> Spent an hour trying to install this software. Eager to get off SyncTerm and onto something else.
> 
> Would love a macOS install script or something. I am running macOS Mojave 10.14.2.

@squintgit 
Are you still having issues?

**Comment by M-griffin** [comment]
This appears to be old now, and no new updates, so goin to close this. feel free to reach out if still having issues.
