### ISSUE TITLE
ctrl+underscore should send ``\x1f``

### ISSUE THREAD

**Issue by jquast** [M-griffin/EtherTerm#8]
sends nothing.

this is used in irssi, for example, to _underline_ text

**Comment by M-griffin** [comment]
ah i was misreading it, i was looking at \x1ff haha but figured it out when i tried showkey in the terminal.  It also doesn't a nice clear line at the terminal,  back spaces the entire line.  I like it.  Done!

**Comment by M-griffin** [comment]
Done.  https://github.com/M-griffin/EtherTerm/commit/285e436d119ada2ebf8c7f88081f36c10ed2ef84
